# Site settings
title: Thuyiya's CV 
description: thusitha thiyushan's cv
favicon: /assets/img/avatar.JPG
baseurl: "" #https://thuyiya.github.io
url: https://thuyiya.github.io
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Thusitha Thiyushan
  title: Game Designer | Web Developer
  address: Kandy, Sri Lanka
  email: thusitha.4t@gmail.com
  link: #thuyiya.lk
  weibo:
  github: thuyiya
  linkedin: thuyiya
  twitter: thusitha4t
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: TSMS | Tea Supply Management System
      location: for Thalapalakanada Tea Factory
      title: git/ php/ javascript/ jQuery/ HTML5/ Bootstrap/ mySql/ balsamiq mockup/ Sms Getway
      started: 15/02
      duration: (2nd Year Group)
      description: Web based Factory Tea Supply Management System and Message alert system. For Tea Factory. system also provide transaction report, bills, monthly transection summery etc.
    - work2:
      company: CPR SIMULATOR | with Virtual Reality
      location: for Colombo General Hospital
      title: Git/ C/ C++ / c#/ Unity3D/ arduino/trello
      started: 16/03
      duration: (3rd Year Project(ongoing))
      description: CPR Simulator with Virtual Reality for, Inability of medical practitioners to get the real experience without actually involved in critical medical situations. 
    - work3:
      company: Hospital Dispatch | General Hospital Colombo
      location: for General Hospital Colombo
      title: git/ JavaEE/ javascript/ jQuery/ HTML5/ Bootstrap/ mySql/ Tomcat
      started: 16/01
      duration: (On Going)
      description: patient queue control/bill generate/ date scheduling/ patient report, history... etc.
  educationHistory:
    - education1:
      organization: University of Colombo School of Computing
      location: 35 Philip Gunewardena Mawatha, Colombo
      degree: Bachelor
      major: Computer Science
      started: 2013
      duration: (2013 - 2016)
      description: Undergraduate BSc in Computer Science.
  languages:
    - language1:
      name: Sinhalese
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
  programmingSkills:
    - skill1:
      name: HTML
      percentage: 90%
    - skill2:
      name: Bootstrap
      percentage: 90%
    - skill3:
      name: JavaScript
      percentage: 70%
    - skill4:
      name: Mean Stack(NodeJs/ExpressJs/AngularJS)
      percentage: 70%
    - skill5:
      name: Java/Java EE
      percentage: 60%
    - skill6:
      name: PHP
      percentage: 90%
    - skill7:
      name: C#
      percentage: 90%
    - skill8:
      name: C/C++
      percentage: 65%


