# Site settings
title: Thuyiya's CV 
description: thusitha thiyushan's cv
favicon: /assets/img/avatar.JPG
baseurl: "" #https://thuyiya.github.io
url: https://thuyiya.github.io
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Thusitha Thiyushan
  title: Game Designer | Web Developer
  address: Kandy, Sri Lanka
  email: thusitha.4t@gmail.com
  link: #thuyiya.lk
  weibo:
  github: thuyiya
  linkedin: thuyiya
  twitter: thusitha4t
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Finzsoft Solutions Ltd
      location: Auckland, New Zealand
      title: Java Developer
      started: 2014
      duration: (2014 - Present)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work2:
      company: Agfa HealthCare
      location: Shanghai, China
      title: Java Developer
      started: 2012
      duration: (2012 - 2014)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work3:
      company: Citigroup Services and Technology (China) Limited
      location: Shanghai, China
      title: Java Developer
      started: 2009
      duration: (2009 - 2012)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: Northeastern University
      location: Shenyang, China
      degree: Bachelor
      major: Software Engineering
      started: 2005
      duration: (2005 - 2009)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  languages:
    - language1:
      name: Sinhalese
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
  programmingSkills:
    - skill1:
      name: HTML
      percentage: 100%
    - skill2:
      name: Bootstrap
      percentage: 90%
    - skill3:
      name: JavaScript
      percentage: 70%
    - skill4:
      name: Mean Stack(NodeJs/ExpressJs/AngularJS)
      percentage: 70%
    - skill5:
      name: Java/Java EE
      percentage: 60%
    - skill6:
      name: PHP
      percentage: 90%
    - skill7:
      name: C#
      percentage: 90%
    - skill8:
      name: C/C++
      percentage: 65%


